# Example execute: ansible-playbook playbook-deploy-docker.yml -i 192.168.200.141, -u ubuntu
- name: Install Docker and Docker Compose
  hosts: all
  become: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
   
    - name: Add Docker repository
      apt_repository:
         repo: "deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
         state: present

    - name: Update Apt packages
      apt:
        update_cache: yes

    - name: Install Docker packages
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add GitHub SSH key
      copy:
        src: files/abb
        dest: /root/.ssh/abb
        owner: root
        group: root
        mode: '0600'
  
    - name: Configure SSH to use ansible key for github.com
      template:
        src: files/ssh_config.j2
        dest: /root/.ssh/config
        owner: root
        group: root
        mode: '0644'

    - name: Add GitHub SSH host key to known_hosts
      shell: ssh-keyscan github.com >> /root/.ssh/known_hosts
        
    - name: Clone a private repository
      git:
        repo: git@github.com:oudjat/abb.git
        key_file: /root/.ssh/abb
        dest: /services/script

    - name: Move connect.sh files to /services/script
      command: "mv /services/script/files/connect.sh /services/script/"

    - name: Move service.sh files to /services/scripts
      command: "mv /services/script/files/service.sh /services/script/"

        
    - name: Start service and check
      command: "/services/script/service.sh start"
      async: 1
      poll: 1
      register: service_status
      ignore_errors: true
  
    - name: Display service status
      debug:
        msg: "Service is {{ 'running' if service_status.rc == 0 else 'not running' }}"

