- name: Install Docker and Docker Compose
  hosts: all
  become: yes

  vars:
    gitlab_repo_url: "https://github.com/oudjat/abb.git"  

  tasks:
    - name: Install dependencies
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
   
    - name: Add Docker repository
      apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable  

    - name: Update Apt packages
      apt:
        update_cache: yes

    - name: Install Docker packages
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        
    - name: Clone or pull the GitLab repository
      git:
        repo: "{{ gitlab_repo_url }}"
        dest: "/services/script"
        version: "main"
        accept_hostkey: yes
        update: yes

    - name: Move connect.sh files to /services/script
      command: "mv /services/script/files/connect.sh /services/script/"

    - name: Move service.sh files to /services/scripts
      command: "mv /services/script/files/service.sh /services/script/"

    - name: Check if the service is running  
      command: "/services/script/service.sh start"
      async: 1 
      poll: 1
      register: service_status
      ignore_errors: true
    
    - name: Display service status
      debug:
        msg: "Service is {{ 'running' if service_status.rc == 0 else 'not running' }}"

